### ISSUE TITLE
Other dependencies missing

### ISSUE THREAD

**Issue by pusewicz** [kamou/gpt-vim#3]
When launching MacVim, I can see these errors:

```
 Error detected while processing /Users/piotr/.vim/pack/packager/start/gpt-vim/plugin/gpt.vim:
line    8:
Traceback (most recent call last):
  File "", line 1, in <module>
  File "/Users/piotr/.vim/pack/packager/start/gpt-vim/python3/gpt.py", line 12, in <module>
    import functions.search as search
  File "/Users/piotr/.vim/pack/packager/start/gpt-vim/python3/functions/search.py", line 1, in <module>
```

**Comment by akhamouma-psee** [comment]
I just added the requirements.txt file to the master branch,
you can install all required deps with:
```
pip install -r requirements.txt
```

**Comment by pusewicz** [comment]
Fantastic, thanks!

**Comment by kamou** [comment]
happy to help, enjoy using the plugin !
